src/Bookshelf_FL/Controllers/BookController.cs
using Bookshelf_FL.Extensions.Services;
using Bookshelf_FL.Extensions.Services.Factories;
using Bookshelf_FL.Extensions.Validators;
using Bookshelf_FL.Extensions.Validators.Models;
using Bookshelf_FL.ViewModels.AccountViewModels;
using Bookshelf_FL.ViewModels.BookViewModels;
using Bookshelf_SL.Repositories;
using Bookshelf_SL.Repositories.IntermediateModelsRepositories;
using Bookshelf_TL.Models;
using Bookshelf_TL.Models.IntermediateModels;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bookshelf_FL.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly IRepository<Book> _bookRepository;
        private readonly UserManager<User> _userManager;
        private readonly CoverImageService _coverImageService;
        private readonly RelationEntitiesService _relationEntitiesService;
        private readonly FactoryOfBookService _factoryOfBookService;
        public BookController(
            IRepository<Book> bookRepository,
            UserManager<User> userManager,
            CoverImageService coverImageService,
            RelationEntitiesService relationEntitiesService,
            FactoryOfBookService factoryOfBookService)
        {
            _bookRepository = bookRepository;
            _userManager = userManager;
            _coverImageService = coverImageService;
            _relationEntitiesService = relationEntitiesService;
            _factoryOfBookService = factoryOfBookService;
        }

        public async Task<IActionResult> GetBooks() 
        {
            var books = _bookRepository.All;

            var currentUser = await _userManager.GetUserAsync(User);

            var bookListViewModels = _factoryOfBookService.BookListViewModels(currentUser, books);

            return View(bookListViewModels);
        }
        public async Task<IActionResult> SearchBook(string SearchQuery) 
        {
            IEnumerable<Book> filteredBooks;

            if (SearchQuery == null)
            {
                filteredBooks = _bookRepository.All;
            }
            else
            {
                filteredBooks = _bookRepository.All.Where(book => (book.BookName != null && book.BookName.Contains(SearchQuery)));
            }

            var currentUser = await _userManager.GetUserAsync(User);

            var bookListViewModels = _factoryOfBookService.BookListViewModels(currentUser, filteredBooks);

            return View(bookListViewModels);
        }
        public async Task<IActionResult> GetBook(string bookId) 
        {
            var book = _bookRepository.FindById(bookId);

            var currentUser = await _userManager.GetUserAsync(User);

            var bookViewModel = _factoryOfBookService.BookViewModel(book, currentUser);

            return View(bookViewModel);
        }
        public IActionResult Create() 
        {
            var bookCreateViewModel = _factoryOfBookService.BookCreateViewModel();

            return View(bookCreateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookCreateViewModel bookCreateViewModel, [FromServices] IValidator<BookCreateViewModel> validator)
        {
            ValidationResult result = await validator.ValidateAsync(bookCreateViewModel);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("Create", bookCreateViewModel);
            }

            Book book = new Book
            {
                Id = Guid.NewGuid().ToString(),
                BookName = bookCreateViewModel.BookName,
                DateOfPublication = bookCreateViewModel.DateOfPublication,
                Series = bookCreateViewModel.Series,
                NumberInSeries = bookCreateViewModel.NumberInSeries,
                Description = bookCreateViewModel.Description,
                AverageBookScore = 0,
            };

            if (bookCreateViewModel.CoverImage != null && bookCreateViewModel.CoverImage.Length > 0)
            {
                string folderToSaveName = "BookCovers";
                book.CoverPath = await _coverImageService.AddCover(bookCreateViewModel.CoverImage, folderToSaveName);
            }

            _bookRepository.Create(book);

            if (bookCreateViewModel.SelectedAuthors != null && bookCreateViewModel.SelectedAuthors.Any())
            {
                _relationEntitiesService.UpdateBookAuthorsInsideBook(book.Id, bookCreateViewModel.SelectedAuthors);
            }

            if (bookCreateViewModel.SelectedCategories != null && bookCreateViewModel.SelectedCategories.Any())
            {
                _relationEntitiesService.UpdateBookCategoriesInsideBook(book.Id, bookCreateViewModel.SelectedCategories);
            }

            return RedirectToAction("GetBook", new { bookId = book.Id });
        }
        public IActionResult Edit(string id) 
        {
            var book = _bookRepository.FindById(id);

            if (book == null)
                return NotFound();

            var bookEditViewModel = _factoryOfBookService.BookEditViewModel(book);

            return View(bookEditViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookEditViewModel bookEditViewModel, [FromServices] IValidator<BookEditViewModel> validator)
        {
            ValidationResult result = await validator.ValidateAsync(bookEditViewModel);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("Edit", bookEditViewModel);
            }

            var book = _bookRepository.FindById(bookEditViewModel.Id);

            book.BookName = bookEditViewModel.BookName != null ? bookEditViewModel.BookName : book.BookName;
            book.DateOfPublication = bookEditViewModel.DateOfPublication;
            book.Series = bookEditViewModel.Series;
            book.NumberInSeries = bookEditViewModel.NumberInSeries;
            book.Description = bookEditViewModel.Description;

            if (bookEditViewModel.SelectedAuthors != null && bookEditViewModel.SelectedAuthors.Any())
            {
                _relationEntitiesService.UpdateBookAuthorsInsideBook(book.Id, bookEditViewModel.SelectedAuthors);
            }

            if (bookEditViewModel.CoverImage != null && bookEditViewModel.CoverImage.Length > 0)
            {
                string folderToSaveName = "BookCovers";
                book.CoverPath = await _coverImageService.AddCover(bookEditViewModel.CoverImage, folderToSaveName);
            }

            _bookRepository.Update(book);

            return RedirectToAction("GetBook", new { bookId = book.Id });
        }

        [HttpPost]
        public IActionResult DeleteImage(string id) 
        {
            var book = _bookRepository.FindById(id);

            _coverImageService.DeleteCover(_bookRepository, book);

            return RedirectToAction("Edit", new { id = id });
        }

        [HttpPost]
        public IActionResult Delete(
            string bookId,
            [FromServices] IIntermediateRepository<BookUser> bookUserRepository,
            [FromServices] IIntermediateRepository<BookAuthor> bookAuthorRepository,
            [FromServices] IIntermediateRepository<BookCategory> bookCategoryRepository
            )
        {
            var book = _bookRepository.FindById(bookId);

            var bookUsers = bookUserRepository.All.Where(ba => ba.BookId == book.Id);
            var bookAuthors = bookAuthorRepository.All.Where(ba => ba.BookId == book.Id);
            var bookCategories = bookCategoryRepository.All.Where(ba => ba.BookId == book.Id);

            if (book == null)
                return NotFound();

            _coverImageService.DeleteCover(_bookRepository, book);

            bookUserRepository.DeleteCollection(bookUsers);
            bookAuthorRepository.DeleteCollection(bookAuthors);
            bookCategoryRepository.DeleteCollection(bookCategories);

            _bookRepository.Delete(book.Id);

            return RedirectToAction("GetBooks");
        }

    }
}

src/Bookshelf_FL/Controllers/BookUserController.cs
using Bookshelf_FL.Extensions.Services;
using Bookshelf_SL.Repositories.IntermediateModelsRepositories;
using Bookshelf_TL.Models;
using Bookshelf_TL.Models.IntermediateModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bookshelf_FL.Controllers
{
    public class BookUserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IIntermediateRepository<BookUser> _bookUserRepository;
        private readonly BookScoreService _bookService;
        public BookUserController(
            UserManager<User> userManager,
            IIntermediateRepository<BookUser> bookUserRepository, 
            BookScoreService bookService)
        {
            _userManager = userManager;
            _bookUserRepository = bookUserRepository;
            _bookService = bookService;
        }
        public async Task<IActionResult> SetStatus(string bookId, string status)
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);

            var bookUser = _bookUserRepository.FindById(bookId, currentUser.Id);

            if (bookUser == null)
            {
                bookUser = new BookUser()
                {
                    BookId = bookId,
                    UserId = currentUser.Id,
                    Status = status
                };

                _bookUserRepository.Create(bookUser);
            }
            else
            {
                if (string.Equals(bookUser.Status, status))
                {
                    bookUser.Status = "";
                }
                else
                {
                    bookUser.Status = status;
                }

                _bookUserRepository.Edit(bookUser);
            }

            var returnUrl = HttpContext.Request.Headers["Referer"].ToString();

            return Redirect(returnUrl);
        }
        public async Task<IActionResult> SetRating(string bookId, int rating, string StatusOfCurrentUser)
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);

            var bookUser = _bookUserRepository.FindById(bookId, currentUser.Id);

            if (bookUser == null)
            {
                bookUser = new BookUser()
                {
                    BookId = bookId,
                    UserId = currentUser.Id,
                };

                _bookUserRepository.Create(bookUser);
            }

            if (rating >= 1 && rating <= 5)
            {
                bookUser.IndividualBookScore = rating;

                _bookUserRepository.Edit(bookUser);
            }
            else
            {
                if (StatusOfCurrentUser == null)
                {
                    _bookUserRepository.Delete(bookUser);
                }
                else
                {
                    bookUser.IndividualBookScore = null;

                    _bookUserRepository.Edit(bookUser);
                }
            }

            _bookService.UpdateAverageBookScore(bookId);

            var returnUrl = HttpContext.Request.Headers["Referer"].ToString();

            return Redirect(returnUrl);
        }

        public IActionResult Remove(string bookId, string userId)
        {
            var bookUser = _bookUserRepository.FindById(bookId, userId);

            _bookUserRepository.Delete(bookUser);

            var returnUrl = HttpContext.Request.Headers["Referer"].ToString();

            return Redirect(returnUrl);
        }

    }
}

src/Bookshelf_FL/Controllers/UserController.cs
using Bookshelf_FL.Extensions.Services;
using Bookshelf_FL.Extensions.Services.Factories;
using Bookshelf_FL.Extensions.Validators;
using Bookshelf_FL.ViewModels.UserViewModels;
using Bookshelf_SL.Repositories;
using Bookshelf_TL.Models;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Bookshelf_FL.Controllers
{
    public class UserController : Controller
    {
        private readonly IRepository<User> _userRepository;
        private readonly IRepository<Book> _bookRepository;
        private readonly CoverImageService _coverImageService;
        private readonly FactoryOfBookService _factoryOfBookService;
        private readonly FactoryOfUserService _factoryOfUserService;
        private readonly IValidator<UserEditViewModel> _userEditViewModelValidator;

        public UserController(
            IRepository<User> usersRepository,
            IRepository<Book> bookRepository,
            CoverImageService coverImageService,
            FactoryOfBookService factoryOfBookService,
            FactoryOfUserService factoryOfUserService,
            IValidator<UserEditViewModel> userEditViewModelValidator
)
        {
            _userRepository = usersRepository;
            _bookRepository = bookRepository;
            _coverImageService = coverImageService;
            _factoryOfBookService = factoryOfBookService;
            _factoryOfUserService = factoryOfUserService;
            _userEditViewModelValidator = userEditViewModelValidator;
        }
        public IActionResult GetUsers()
        {
            var users = _userRepository.All;

            var userListViewModels = _factoryOfUserService.UserListViewModels(users);

            return View(userListViewModels);
        }
        public IActionResult SearchUser(string SearchQuery)
        {
            IEnumerable<User> filteredUsers;

            if (SearchQuery == null)
            {
                filteredUsers = _userRepository.All;
            }
            else
            {
                filteredUsers = _userRepository.All
                .Where(user =>
                    (user.FirstName != null && user.FirstName.Contains(SearchQuery))
                    || (user.MiddleName != null && user.MiddleName.Contains(SearchQuery))
                    || (user.LastName != null && user.LastName.Contains(SearchQuery))
                    || (user.UserName != null && user.UserName.Contains(SearchQuery)));
            }

            var userListViewModels = _factoryOfUserService.UserListViewModels(filteredUsers);

            return View(userListViewModels);
        }
        public IActionResult GetUser(string userId)
        {
            var user = _userRepository.FindById(userId);

            if (user == null)
                return NotFound();

            var booksOfUser = _bookRepository.All
                .Where(
                    book => book.BookUsers != null &&
                    book.BookUsers.Any(bookUser => bookUser.UserId == user.Id))
                .ToList();

            var bookListOfUserViewModel = _factoryOfBookService.BookListViewModels(user, booksOfUser);

            var userViewModel = _factoryOfUserService.UserViewModel(user, bookListOfUserViewModel);

            return View(userViewModel);
        }

        public IActionResult Edit(string userId)
        {
            var user = _userRepository.FindById(userId);

            if (user == null)
                return NotFound();

            var userSetUpViewModel = _factoryOfUserService.UserEditViewModel(user);

            return View(userSetUpViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditViewModel userSetUpViewModel)
        {
            ValidationResult result = await _userEditViewModelValidator.ValidateAsync(userSetUpViewModel);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View("Edit", userSetUpViewModel);
            }

            var user = _userRepository.FindById(userSetUpViewModel.Id);

            if (user == null)
                return NotFound();

            user.FirstName = userSetUpViewModel.FirstName != null ? userSetUpViewModel.FirstName : user.FirstName;
            user.MiddleName = userSetUpViewModel.MiddleName;
            user.LastName = userSetUpViewModel.LastName;
            user.UserName = userSetUpViewModel.UserName;
            user.Email = userSetUpViewModel.Email;
            user.PhoneNumber = userSetUpViewModel.PhoneNumber;
            user.Description = userSetUpViewModel.Description;
            user.BirthDate = userSetUpViewModel.BirthDate;


            if (userSetUpViewModel.CoverImage != null && userSetUpViewModel.CoverImage.Length > 0)
            {
                string folderToSaveName = "UserCovers";
                user.CoverPath = await _coverImageService.AddCover(userSetUpViewModel.CoverImage, folderToSaveName);
            }

            _userRepository.Update(user);

            return RedirectToAction("GetUser", new { userId = user.Id });

        }

        [HttpPost]
        public IActionResult DeleteImage(string id)
        {
            var user = _userRepository.FindById(id);

            _coverImageService.DeleteCover(_userRepository, user);

            return RedirectToAction("Edit", new { userId = id });
        }
    }
}

src/Bookshelf_FL/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html>

<head>
    <!-- Мета-теги, стилі та інші ресурси -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="/css/_Layout.css" />
    <link rel="stylesheet" href="/css/GetItem.css" />
    <link rel="stylesheet" href="/css/MainGrid.css" />

    <title>@ViewBag.Title</title>
</head>

<body>
    <header>
        @if (SignInManager.IsSignedIn(User))
        {
            <div id="Container">


                <a href="/" class="item">
                    <div class="styled-link">
                        Додому
                    </div>
                </a>

                <a asp-controller="Book" asp-action="GetBooks" class="item">
                    <div class ="styled-link">
                        Книги
                    </div>
                </a>

                <a asp-controller="Author" asp-action="GetAuthors" class="item">
                    <div class="styled-link">
                        Автори
                    </div>
                </a>

                <a asp-controller="User" asp-action="GetUsers" class="item">
                    <div class="styled-link">
                        Користувачі
                    </div>
                </a>

                @if (User.IsInRole("admin"))
                {
                    <a asp-controller="Admin" asp-action="Index" class="item">
                        <div class="styled-link">
                            Адмінпанель
                        </div>
                    </a>
                }

                <a asp-controller="Account" asp-action="Logout" class="item">
                    <div class="styled-link">
                        Log out
                    </div>
                </a>


            </div>
        }

        @RenderSection("Header", false)
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
        @RenderSection("Footer", false)
    </footer>

    <script>
        @RenderSection("Script", false)
    </script>

</body>
</html>

src/Bookshelf_FL/Views/Shared/_ListOfAuthorsPartial.cshtml
@model IEnumerable<Bookshelf_FL.ViewModels.AuthorViewModels.AuthorListViewModel>

@foreach (var author in Model.OrderBy(b => b.FirstName))
{
    <div class="ItemsOfBookList">

        <div class="CoverOfItemsOfBookList">

            @if (!string.IsNullOrEmpty(author.CoverPath))
            {
                <img src="@Url.Content(author.CoverPath)" alt="@author.FirstName @author.LastName" />
            }
            else
            {
                <img src="~/defaultFiles/DefaultAuthor.jpg" alt="@author.FirstName @author.LastName" />
            }

        </div>

        <a href="@Url.Action("GetAuthor", "Author", new { authorId = author.Id })" Class="linkOfOfItemsOfBookList">@author.FirstName @author.LastName</a>

    </div>
}

src/Bookshelf_FL/Views/Shared/_ListOfBooksPartial.cshtml
@model IEnumerable<Bookshelf_FL.ViewModels.BookViewModels.BookListViewModel>

@foreach (var book in Model.OrderByDescending(b => b.Series).ThenBy(b => b.NumberInSeries))
{
    <div class="ItemsOfBookList">

        <div class="CoverOfItemsOfBookList">

            @if (!string.IsNullOrEmpty(book.CoverPath))
            {
                <img src="@Url.Content(book.CoverPath)" alt="@book.BookName" />
            }
            else
            {
                <img src="~/defaultFiles/DefaultBook.jpg" alt="@book.BookName" />
            }

        </div>

        <a href="@Url.Action("GetBook", "Book", new { bookId = @book.Id })" Class="linkOfOfItemsOfBookList">@book.BookName</a>

    </div>
}

src/Bookshelf_FL/Views/Shared/_ListOfUsersPartial.cshtml
@model IEnumerable<Bookshelf_FL.ViewModels.UserViewModels.UserListViewModel>

@foreach (var user in Model.OrderBy(b => b.LastName))
{
    <div class="ItemsOfBookList">

        <div class="CoverOfItemsOfBookList">

            @if (!string.IsNullOrEmpty(user.CoverPath))
            {
                <img src="@Url.Content(user.CoverPath)" alt="@user.FirstName @user.LastName" />
            }
            else
            {
                <img src="~/defaultFiles/DefaultUser.jpg" alt="@user.FirstName @user.LastName" />
            }

        </div>

        <a href="@Url.Action("GetUser", "User", new { userId = user.Id })" Class="linkOfOfItemsOfBookList">@user.FirstName @user.LastName</a>

    </div>
}

src/Bookshelf_FL/Views/Shared/_StatusOfCurrentUserSelectorPartial.cshtml
@model Bookshelf_FL.ViewModels.BookViewModels.BookViewModel

@switch (Model.StatusOfCurrentUser)
{
    case "Прочитано":
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Прочитано" style="color: green;">Прочитано</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Читаю" style="color: gray;">Читаю</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Хочу прочитати" style="color: gray;">Хочу прочитати</a>
        break;
    case "Читаю":
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Прочитано" style="color: gray;">Прочитано</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Читаю" style="color: green;">Читаю</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Хочу прочитати" style="color: gray;">Хочу прочитати</a>
        break;
    case "Хочу прочитати":
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Прочитано" style="color: gray;">Прочитано</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Читаю" style="color: gray;">Читаю</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Хочу прочитати" style="color: green;">Хочу прочитати</a>
        break;
    default:
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Прочитано" style="color: gray;">Прочитано</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Читаю" style="color: gray;">Читаю</a>
        <a asp-action="SetStatus" asp-controller="BookUser" asp-route-bookId="@Model.Id" asp-method="post" class="Selector" asp-route-status="Хочу прочитати" style="color: gray;">Хочу прочитати</a>
        break;
}